#! python


def build(ctx):

    ctx(
        features="run_py_script",
        source="create_comparison_plot.py",
        deps=[
            ctx.path_to(ctx, "IN_ANALYSIS", "true_df.csv"),
            ctx.path_to(ctx, "OUT_ANALYSIS", "21_calculated_df.csv"),
        ],
        target=ctx.path_to(ctx, "OUT_FIGURES", "comparison_plots.html"),
    )

    from src.final.project_dependency_graph import make_project_dependency_graph

    ctx.add_post_fun(make_project_dependency_graph)
